name: Build & Publish SDKs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    permissions: write-all
    strategy:
      matrix:
        sdk:
          - redux
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch & Pull
        run: |
          git fetch
          git pull

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/

      - name: Install
        run: yarn --no-immutable

      - name: Build SDK
        run: yarn build:sdk:${{ matrix.sdk }}

      - name: Populate .npmrc
        run: |
          cd generated/${{ matrix.sdk }}
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Deploy 🚀
        run: cd generated/${{ matrix.sdk }} && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}